In [74]:
import numpy as np
import pandas as pd

In [77]:
x = np.array([1, 4, 2, 5, 3])
np.sin(x)



array([ 0.84147098, -0.7568025 ,  0.90929743, -0.95892427,  0.14112001])

In [3]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [58]:
x1 = np.random.randint(10, size = 6)
x1
r = np.random.random((3,3))
r
r.itemsize

8

In [10]:
x2 = np.random.randint(10, size = (3, 4))
x2

array([[7, 7, 1, 7],
       [0, 6, 2, 8],
       [5, 9, 3, 0]])

In [13]:
x3 = np.random.randint(10, size = (3, 4, 5))
x3

array([[[2, 1, 2, 5, 3],
        [8, 5, 5, 1, 0],
        [5, 0, 2, 7, 1],
        [9, 4, 6, 5, 6]],

       [[6, 7, 7, 4, 1],
        [5, 8, 9, 8, 3],
        [4, 2, 1, 2, 5],
        [2, 9, 0, 5, 5]],

       [[8, 9, 4, 4, 1],
        [9, 7, 5, 4, 3],
        [7, 1, 2, 5, 7],
        [2, 6, 9, 0, 7]]])

In [14]:
x3.ndim

3

In [15]:
x2.ndim

2

In [16]:
x1.ndim

1

In [17]:
x3.shape

(3, 4, 5)

In [18]:
x3.size

60

In [19]:
x1

array([0, 9, 2, 4, 9, 8])

In [20]:
x1[0]

0

In [21]:
x1[3]

4

In [23]:
x1[-1]

8

In [24]:
x1[0:2]

array([0, 9])

In [25]:
x1[1:2]

array([9])

In [26]:
x4 = np.array(40)
x4.ndim

0

In [67]:
x = np.random.randint(100, size = 10)
x1,x2,x3 = np.split(x1,[3,5])
print(x)
print(x1,x2,x3)

[74 61 27 45 48 63 90 97 24 26]
[5 9 9] [] []


In [33]:
x[[3,4,5]]

array([10, 15,  9])

In [34]:
x4 = np.random.randint(100, size = (3,4))

In [35]:
x4

array([[55, 26, 47, 71],
       [89, 46, 67, 53],
       [ 8, 97, 42, 57]])

In [42]:
x4[[0,2], [1,2]]

array([26, 42])

In [45]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],index = ['a','b','c', 'c'] )
data
d= pd.Series(5, index=[100, 200, 300])
d 



100    5
200    5
300    5
dtype: int64

In [36]:
data1 = pd.Series((5, 7, 7), index=[100, 200, 300])
data1

100    5
200    7
300    7
dtype: int64

In [37]:
data3 = pd.Series({2:'a', 1:'b', 3:'c'})
data3

2    a
1    b
3    c
dtype: object

In [38]:
data4 = pd.Series({2:'a', 1:'b', 3:'c'}, index=[3, 2])
data4

3    c
2    a
dtype: object

In [39]:
x1 = np.random.randint(10, size=6)
x1

array([8, 6, 3, 0, 5, 4])

In [40]:
data5 = np.arange(0, 5, 0.5, dtype=int)
data5

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [41]:
x = np.arange( 6)
print("x =", x) 
print("x + 5 =", x + 5) 
print("x - 5 =", x - 5) 
print("x * 2 =", x * 2) 
print("x / 2 =", x / 2) 
print("x // 2 =", x // 2)
print(np.add(x,5))




x = [0 1 2 3 4 5]
x + 5 = [ 5  6  7  8  9 10]
x - 5 = [-5 -4 -3 -2 -1  0]
x * 2 = [ 0  2  4  6  8 10]
x / 2 = [0.  0.5 1.  1.5 2.  2.5]
x // 2 = [0 0 1 1 2 2]
[ 5  6  7  8  9 10]


In [72]:
data7 = np.linspace(1,10,10,dtype = int)
data7
x1,x2,x3 = np.split(data7,[3,5])
print(x1,x2,x3)

[1 2 3] [4 5] [ 6  7  8  9 10]


In [43]:
x = np.array([1, 2, 3]) 
y = np.array([3, 2, 1]) 
np.concatenate([x, y])
z = [99, 99, 99] 
print(np.concatenate([x, y, z]))


[ 1  2  3  3  2  1 99 99 99]


In [44]:
a = np.array([[0,0,0],[10,10,10],[20,20,20],[30,30,30]]) 
b = np.array([0,1,2]) 
print(np.add(a,b))

[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]


In [47]:
population_dict = {'California': 38332521, 'Texas': 26448193, 'New York': 19651127, 'Florida': 19552860, 'Illinois': 12882135} 
population = pd.Series(population_dict) 
population


California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [49]:
area_dict = {'California': 423967, 'Texas': 695662, 'New York': 141297, 'Florida': 170312, 'Illinois': 149995}
area = pd.Series(area_dict) 
area


California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
dtype: int64

In [50]:
states = pd.DataFrame({'population': population, 'area': area}) 
states


population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995